version: '3.4'

services:
  reelables-api-fake:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
    ports:
      - "8180"

  neonesync-service:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  tracking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8280
      - BASE_PATH="http://reelables-api-fake:8180/v1/" 
    ports:
      - "8280"

