version: '3.4'
include:
    - path :
        - NeOneServer/docker-compose/docker-compose.yml

services:
  sql-server-db:
      container_name: sql-server-db
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: "Shenzhen2024!"
        ACCEPT_EULA: "Y"
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  reelables.api.fake:
    image: ${DOCKER_REGISTRY-}reelablesapifake
    build:
      context: .
      dockerfile: Reelables.Api.Fake/Dockerfile
    ports:
        - "18001:8080"
  neonesync.service:
    image: ${DOCKER_REGISTRY-}neonesyncservice
    build:
      context: .
      dockerfile: NeOneSync.Service/Dockerfile


  tracking.api:
    image: ${DOCKER_REGISTRY-}trackingapi
    build:
      context: .
      dockerfile: Tracking.Api/Dockerfile
    ports:
        - "18000:8080"
