version: '3.4'

services:
  reelables-api-fake:
    image: ${DOCKER_REGISTRY-}reelablesapifake
    build:
      context: .
      dockerfile: Reelables.Api.Fake/Dockerfile
    ports:
        - "18001:8180"
    networks:
      - hackathon
 
  neonesync-service:
    image: ${DOCKER_REGISTRY-}neonesyncservice
    build:
      context: .
      dockerfile: NeOneSync.Service/Dockerfile
    networks:
      - hackathon

  tracking-api:
    image: ${DOCKER_REGISTRY-}trackingapi
    build:
      context: .
      dockerfile: Tracking.Api/Dockerfile
    ports:
        - "18000:8280"
    networks:
      - hackathon
    environment:
      - REELABLES_BASE_URL=http://reelables-api-fake:8180/v1
    depends_on:
      - reelables-api-fake

networks:
  hackathon:
    external: true