version: '3.4'

services:
  reelables-api-fake:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
    ports:
      - "8180"

  neonesync-service:
    environment:
      - DOTNET_ENVIRONMENT=Development

  tracking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8280
      - BASE_PATH="http://reelablesapi:8180/v1/" 
    ports:
      - "8280"

