version: '3.4'
include:
    - path :
        - NeOneServer/docker-compose/docker-compose.yml

services:
  sql-server-db:
      container_name: sql-server-db
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: "Shenzhen2024!"
        ACCEPT_EULA: "Y"
      extra_hosts:
        - "host.docker.internal:host-gateway"
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      extra_hosts:
        - "host.docker.internal:host-gateway"
  reelables-api-fake:
    image: ${DOCKER_REGISTRY-}reelablesapifake
    build:
      context: .
      dockerfile: Reelables.Api.Fake/Dockerfile
    ports:
        - "18001:8180"
    networks:
      - my_network
 
  neonesync-service:
    image: ${DOCKER_REGISTRY-}neonesyncservice
    build:
      context: .
      dockerfile: NeOneSync.Service/Dockerfile
    networks:
      - my_network

  tracking-api:
    image: ${DOCKER_REGISTRY-}trackingapi
    build:
      context: .
      dockerfile: Tracking.Api/Dockerfile
    ports:
        - "18000:8080"
    networks:
      - my_network
    environment:
      - BASE_PATH=http://reelables-api-fake:8180/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  my_network:
    driver: bridge
