version: '3.4'

services:
  sql-server-db:
      container_name: sql-server-db
      image: mcr.microsoft.com/mssql/server:2022-latest
      hostname: sqlserver
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: "Shenzhen2024!"
        ACCEPT_EULA: "Y"
      networks:
        - hackathon
  rabbitmq:
      image: rabbitmq:3-management-alpine
      hostname: rabbitmq
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

networks:
  hackathon:
    external: true