/**
 * Tracking.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlightModel } from './flightModel';
import { Volume } from './volume';
import { MeasuredTemperature } from './measuredTemperature';
import { Weight } from './weight';


export interface PieceDto { 
    id?: string | null;
    currentTemperature?: number | null;
    isTemperatureControlled?: boolean;
    location?: string | null;
    weight?: Weight;
    volume?: Volume;
    flight?: FlightModel;
    alertType?: string | null;
    temperatureHistory?: Array<MeasuredTemperature> | null;
}

