/*
 * Reelables API
 *
 * RESTful API for communicating with the Reelables Platform.
 *
 * The version of the OpenAPI document: 1.2.7
 * Contact: team@reelables.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Reelables.Api.Fake.Models;

/// <summary>
/// Spaces to create in the Workspace
/// </summary>
[DataContract]
public partial class WorkspaceSpacesInput : IEquatable<WorkspaceSpacesInput>
{
    /// <summary>
    /// Gets or Sets Spaces
    /// </summary>
    [Required]
    [DataMember(Name="spaces", EmitDefaultValue=false)]
    public List<WorkspaceSpacesInputSpacesInner> Spaces { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class WorkspaceSpacesInput {\n");
        sb.Append("  Spaces: ").Append(Spaces).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((WorkspaceSpacesInput)obj);
    }

    /// <summary>
    /// Returns true if WorkspaceSpacesInput instances are equal
    /// </summary>
    /// <param name="other">Instance of WorkspaceSpacesInput to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(WorkspaceSpacesInput other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;

        return 
        (
            Spaces == other.Spaces ||
            Spaces != null &&
            other.Spaces != null &&
            Spaces.SequenceEqual(other.Spaces)
        );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Spaces != null)
                hashCode = hashCode * 59 + Spaces.GetHashCode();
            return hashCode;
        }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(WorkspaceSpacesInput left, WorkspaceSpacesInput right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(WorkspaceSpacesInput left, WorkspaceSpacesInput right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
}