/*
 * Reelables API
 *
 * RESTful API for communicating with the Reelables Platform.
 *
 * The version of the OpenAPI document: 1.2.7
 * Contact: team@reelables.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SpaceGateway
    /// </summary>
    [DataContract(Name = "SpaceGateway")]
    public partial class SpaceGateway : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpaceGateway" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SpaceGateway() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SpaceGateway" /> class.
        /// </summary>
        /// <param name="isStatic">Indicate whether the Gateway is statically located.</param>
        /// <param name="latitude">Latitude value of the coordinate. Example: 51.123.</param>
        /// <param name="hasPendingCommands">Indicate whether there are pending commands for the Gateway.</param>
        /// <param name="rssiFilter">rssiFilter.</param>
        /// <param name="gatewayId">Gateway identifier. Example: &#39;e00fce315222e588e1d7482b&#39; (required).</param>
        /// <param name="addedOn">Date that the Gateway was linked to the Space, in UTC. Example: &#39;2019-07-21T17:32:28Z&#39; (required).</param>
        /// <param name="longitude">Longitude value of the coordinate. Example: -0.123.</param>
        public SpaceGateway(bool isStatic = default(bool), float latitude = default(float), bool hasPendingCommands = default(bool), SpaceGatewayRssiFilter rssiFilter = default(SpaceGatewayRssiFilter), string gatewayId = default(string), DateTime addedOn = default(DateTime), float longitude = default(float))
        {
            // to ensure "gatewayId" is required (not null)
            if (gatewayId == null)
            {
                throw new ArgumentNullException("gatewayId is a required property for SpaceGateway and cannot be null");
            }
            this.GatewayId = gatewayId;
            this.AddedOn = addedOn;
            this.IsStatic = isStatic;
            this.Latitude = latitude;
            this.HasPendingCommands = hasPendingCommands;
            this.RssiFilter = rssiFilter;
            this.Longitude = longitude;
        }

        /// <summary>
        /// Indicate whether the Gateway is statically located
        /// </summary>
        /// <value>Indicate whether the Gateway is statically located</value>
        [DataMember(Name = "isStatic", EmitDefaultValue = true)]
        public bool IsStatic { get; set; }

        /// <summary>
        /// Latitude value of the coordinate. Example: 51.123
        /// </summary>
        /// <value>Latitude value of the coordinate. Example: 51.123</value>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public float Latitude { get; set; }

        /// <summary>
        /// Indicate whether there are pending commands for the Gateway
        /// </summary>
        /// <value>Indicate whether there are pending commands for the Gateway</value>
        [DataMember(Name = "hasPendingCommands", EmitDefaultValue = true)]
        public bool HasPendingCommands { get; set; }

        /// <summary>
        /// Gets or Sets RssiFilter
        /// </summary>
        [DataMember(Name = "rssiFilter", EmitDefaultValue = false)]
        public SpaceGatewayRssiFilter RssiFilter { get; set; }

        /// <summary>
        /// Gateway identifier. Example: &#39;e00fce315222e588e1d7482b&#39;
        /// </summary>
        /// <value>Gateway identifier. Example: &#39;e00fce315222e588e1d7482b&#39;</value>
        [DataMember(Name = "gatewayId", IsRequired = true, EmitDefaultValue = true)]
        public string GatewayId { get; set; }

        /// <summary>
        /// Date that the Gateway was linked to the Space, in UTC. Example: &#39;2019-07-21T17:32:28Z&#39;
        /// </summary>
        /// <value>Date that the Gateway was linked to the Space, in UTC. Example: &#39;2019-07-21T17:32:28Z&#39;</value>
        [DataMember(Name = "addedOn", IsRequired = true, EmitDefaultValue = true)]
        public DateTime AddedOn { get; set; }

        /// <summary>
        /// Longitude value of the coordinate. Example: -0.123
        /// </summary>
        /// <value>Longitude value of the coordinate. Example: -0.123</value>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public float Longitude { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpaceGateway {\n");
            sb.Append("  IsStatic: ").Append(IsStatic).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  HasPendingCommands: ").Append(HasPendingCommands).Append("\n");
            sb.Append("  RssiFilter: ").Append(RssiFilter).Append("\n");
            sb.Append("  GatewayId: ").Append(GatewayId).Append("\n");
            sb.Append("  AddedOn: ").Append(AddedOn).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Latitude (float) maximum
            if (this.Latitude > (float)90)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Latitude, must be a value less than or equal to 90.", new [] { "Latitude" });
            }

            // Latitude (float) minimum
            if (this.Latitude < (float)-90)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Latitude, must be a value greater than or equal to -90.", new [] { "Latitude" });
            }

            // GatewayId (string) maxLength
            if (this.GatewayId != null && this.GatewayId.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for GatewayId, length must be less than 50.", new [] { "GatewayId" });
            }

            if (this.GatewayId != null) {
                // GatewayId (string) pattern
                Regex regexGatewayId = new Regex(@"^[-_A-Za-z0-9]*$", RegexOptions.CultureInvariant);
                if (!regexGatewayId.Match(this.GatewayId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for GatewayId, must match a pattern of " + regexGatewayId, new [] { "GatewayId" });
                }
            }

            // AddedOn (DateTime) maxLength
            if (this.AddedOn != null && this.AddedOn.Length > 20)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AddedOn, length must be less than 20.", new [] { "AddedOn" });
            }

            if (this.AddedOn != null) {
                // AddedOn (DateTime) pattern
                Regex regexAddedOn = new Regex(@"^[0-9TZ:-]*$", RegexOptions.CultureInvariant);
                if (!regexAddedOn.Match(this.AddedOn).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AddedOn, must match a pattern of " + regexAddedOn, new [] { "AddedOn" });
                }
            }

            // Longitude (float) maximum
            if (this.Longitude > (float)180)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Longitude, must be a value less than or equal to 180.", new [] { "Longitude" });
            }

            // Longitude (float) minimum
            if (this.Longitude < (float)-180)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Longitude, must be a value greater than or equal to -180.", new [] { "Longitude" });
            }

            yield break;
        }
    }

}
