/*
 * Reelables API
 *
 * RESTful API for communicating with the Reelables Platform.
 *
 * The version of the OpenAPI document: 1.2.7
 * Contact: team@reelables.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WorkspaceAssetsInputAssetsInner
    /// </summary>
    [DataContract(Name = "WorkspaceAssetsInput_assets_inner")]
    public partial class WorkspaceAssetsInputAssetsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceAssetsInputAssetsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkspaceAssetsInputAssetsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceAssetsInputAssetsInner" /> class.
        /// </summary>
        /// <param name="name">The name of the Asset (required).</param>
        /// <param name="nfcId">Label NFC identifier, used when creating an Asset and linking a Label at the same time. Example: &#39;0000007B&#39;.</param>
        public WorkspaceAssetsInputAssetsInner(string name = default(string), string nfcId = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for WorkspaceAssetsInputAssetsInner and cannot be null");
            }
            this.Name = name;
            this.NfcId = nfcId;
        }

        /// <summary>
        /// The name of the Asset
        /// </summary>
        /// <value>The name of the Asset</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Label NFC identifier, used when creating an Asset and linking a Label at the same time. Example: &#39;0000007B&#39;
        /// </summary>
        /// <value>Label NFC identifier, used when creating an Asset and linking a Label at the same time. Example: &#39;0000007B&#39;</value>
        [DataMember(Name = "nfcId", EmitDefaultValue = false)]
        public string NfcId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkspaceAssetsInputAssetsInner {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NfcId: ").Append(NfcId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 500.", new [] { "Name" });
            }

            if (this.Name != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^[a-zA-Z0-9!@#$&()\-`.+,/"" ]*$", RegexOptions.CultureInvariant);
                if (!regexName.Match(this.Name).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            // NfcId (string) maxLength
            if (this.NfcId != null && this.NfcId.Length > 20)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NfcId, length must be less than 20.", new [] { "NfcId" });
            }

            if (this.NfcId != null) {
                // NfcId (string) pattern
                Regex regexNfcId = new Regex(@"^[a-zA-Z0-9]*$", RegexOptions.CultureInvariant);
                if (!regexNfcId.Match(this.NfcId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NfcId, must match a pattern of " + regexNfcId, new [] { "NfcId" });
                }
            }

            yield break;
        }
    }

}
